config/routes.rb
FflTracker::Application.routes.draw do
  
  resources :admins

  resources :sessions, only: [:new, :create, :destroy]
  match 'login' => 'sessions#new', :as => :login
  match 'exit' => 'sessions#destroy', :as => :logout

  root to: 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  
  validates_presence_of :first_name, :last_name, :email, :password, :password_confirmation
  validates_uniqueness_of :email

  def remove_sensitive_error_messages
    self.errors.full_messages.delete_if { |error| error =~ /digest/ }
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  def index
    @admins = Admin.all
    # only visible to master admin (ME!)
    # how to create master admin session to have access to all pages on site?
  end

  def new
    @admin = Admin.new
    # link to from 'create new league' button on homepage
  end

  def create
    @admin = Admin.new(params[:admin])
    if @admin.save
      create_session(@admin)
      redirect_to admin_path(@admin)
    else
      flash.now[:errors] = @admin.remove_sensitive_error_messages
      render :new
    end
  end

  def show
    @admin = Admin.find(params[:id])
    # page to show all current leagues for a particular admin
    # also include link to create a new league
    # sessions enabled so page is only visible to that admin
    # if anyone but that admin tries to view this page, redirect to root
  end

  def edit
    @admin = Admin.find(params[:id])
    # form to edit admin settings
    # could eventually include email notification settings
    # sessions enabled so page is only visible to that admin
    # if anyone but that admin tries to view this page, redirect to root
  end

  def update
    @admin = Admin.find(session[:admin_id])
    @admin.assign_attributes(params[:admin])
    if @admin.save
      redirect_to admin_path(@admin)
    else
      flash.now[:errors] = @admin.remove_sensitive_error_messages
      render :edit
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def create_session(admin)
    session[:admin_id] = admin.id
  end

  def current_user
    if session[:admin_id]
      @current_user = Admin.find(session[:admin_id])
    end
  end

  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # homepage for app
    # includes login section and button to create new league
    # could also include area to enter in league num and go to that page
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	@admin = Admin.find_by_email(params[:session][:email])
  	if @admin && @admin.authenticate(params[:session][:password])
  		create_session(@admin)
  		redirect_to admin_path(@admin)
  	else
  		flash.now[:errors] = ['Invalid email/password combination']
  		render :new
  	end
  end

  def destroy
  	session.clear
  	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name%>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/admins/edit.html.erb
<p>Edit your settings</p>

<%= render 'form' %>

app/views/admins/index.html.erb
<p>This is the master dashboard</p>

<table id="master-admins-table" border="1">
  <tr id="admins-table-header">
    <td>ID</td>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Email</td>
  </tr>
<% @admins.each do |admin| %>
  <tr class="admin-row">
    <td><%= link_to admin.id, admin_path(admin) %></td>
    <td><%= admin.first_name %></td>
    <td><%= admin.last_name %></td>
    <td><%= mail_to admin.email %></td>
  </tr>
<% end %>
</table>

app/views/admins/new.html.erb
<p>Become an admin!</p>

<%= render 'form' %>

app/views/admins/show.html.erb
<p>Welcome, <%= @admin.first_name %>!</p>

app/views/home/index.html.erb
<h1>FFL TRACKER!!!</h1>

<%= link_to 'Create Admin', new_admin_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FflTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= link_to "Logout", logout_path %>
<% else %>
	<%= link_to "Login", login_path %>
<% end %>

<%= yield %>

<div class="messages">
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p class="errors"><%= error %></p>
    <% end %>
  <% end %>
</div>

</body>
</html>